In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv( "../data/raw/laptop_data.csv" )
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [3]:
df.sample(5)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
367,367,Lenovo,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,No OS,2.4kg,43103.52
365,365,HP,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,8GB,2TB HDD,Intel HD Graphics 405,Windows 10,2.04kg,20725.92
212,212,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,500GB HDD,Intel HD Graphics 520,No OS,2.1kg,18594.72
99,99,HP,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,12GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.62kg,66546.72
1064,1064,MSI,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,1.8kg,102777.12

In [4]:
df=df.drop(columns=["Unnamed: 0"])

In [5]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [6]:
df.sample(5)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
616,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,128GB SSD,AMD Radeon R5 M420,Linux,2.18kg,30316.3200
1180,Lenovo,2 in 1 Convertible,14.0,IPS Panel Touchscreen 2560x1440,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.36kg,87219.3600
367,Lenovo,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,No OS,2.4kg,43103.5200
738,MSI,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,1.8kg,111593.8944
1012,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.48kg,84715.2000

In [7]:
df["Company"].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [8]:
df["Inches"].value_counts()

Inches
15.6    665
14.0    197
13.3    164
17.3    164
12.5     39
11.6     33
13.5      6
12.0      6
13.9      6
12.3      5
10.1      4
15.4      4
15.0      4
13.0      2
18.4      1
17.0      1
14.1      1
11.3      1
Name: count, dtype: int64

# `Feature Engineering`

In [9]:
df["ScreenResolution"].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2304x1440                 6
IPS Panel Retina Display 2560x1600                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
1440x900                                           4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
2560x1440                                          3
Touchscreen 2400x1600                              3
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Full HD 2160x1440                        2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 1366x768                         1
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [10]:
def is_touch_screen(value:str):
    if "Touchscreen" in value:
        return True
    else: return False

In [11]:
is_touch_screen("IPS Panel 2560x1440")

False

In [12]:
df["ScreenResolution"].apply(is_touch_screen)

0       False
1       False
2       False
3       False
4       False
        ...
1298     True
1299     True
1300    False
1301    False
1302    False
Name: ScreenResolution, Length: 1303, dtype: bool

In [13]:
df.insert(
    4,
    "is_touch_screen",
    df["ScreenResolution"].apply(is_touch_screen)

)

In [14]:
df["ScreenResolution"]

0               IPS Panel Retina Display 2560x1600
1                                         1440x900
2                                Full HD 1920x1080
3               IPS Panel Retina Display 2880x1800
4               IPS Panel Retina Display 2560x1600
                           ...
1298     IPS Panel Full HD / Touchscreen 1920x1080
1299    IPS Panel Quad HD+ / Touchscreen 3200x1800
1300                                      1366x768
1301                                      1366x768
1302                                      1366x768
Name: ScreenResolution, Length: 1303, dtype: object

In [15]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [16]:
def is_HD(value:str):
    if "HD" in value:
        return True
    else: return False

In [17]:
df["ScreenResolution"].apply(is_HD)

0       False
1       False
2        True
3       False
4       False
        ...
1298     True
1299     True
1300    False
1301    False
1302    False
Name: ScreenResolution, Length: 1303, dtype: bool

In [18]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [19]:
df.insert(
    5,
    "is_HD",
    df["ScreenResolution"].apply(is_HD)

)

In [20]:
def get_width(value: str):

    value = value.split("x")[0].split(" ")[-1]
    return int(value)

get_width("1366x768	/")

1366

In [21]:
df["ScreenResolution"].apply(get_width)

0       2560
1       1440
2       1920
3       2880
4       2560
        ...
1298    1920
1299    3200
1300    1366
1301    1366
1302    1366
Name: ScreenResolution, Length: 1303, dtype: int64

In [22]:
df.insert(
    6,
    "width",
    df["ScreenResolution"].apply(get_width)


)

In [23]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,is_HD,width,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,False,1440,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,True,1920,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,False,2880,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,True,1920,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,True,3200,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,False,1366,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,False,1366,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,False,1366,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [24]:
def get_height(value: str):

    value = value.split("x")[1]
    return int(value)

get_width("IPS Panel Quad HD+ / Touchscreen 3200x1800")

3200

In [25]:
df.insert(
    7,
    "height",
     df["ScreenResolution"].apply(get_height)


)

In [26]:
df["Cpu"]

0                       Intel Core i5 2.3GHz
1                       Intel Core i5 1.8GHz
2                 Intel Core i5 7200U 2.5GHz
3                       Intel Core i7 2.7GHz
4                       Intel Core i5 3.1GHz
                        ...
1298              Intel Core i7 6500U 2.5GHz
1299              Intel Core i7 6500U 2.5GHz
1300    Intel Celeron Dual Core N3050 1.6GHz
1301              Intel Core i7 6500U 2.5GHz
1302    Intel Celeron Dual Core N3050 1.6GHz
Name: Cpu, Length: 1303, dtype: object

In [27]:
def get_cpu_ghz(value: str):

    value = value.split(" ")[-1].replace("GHz","")
    return float(value)
get_cpu_ghz("Intel Celeron Dual Core N3050 1.6GHz")

1.6

In [28]:
df.insert(
    9,
    "cpu_GHz",
    df["Cpu"].apply(get_cpu_ghz)
)

In [29]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,is_HD,width,height,Cpu,cpu_GHz,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 2.3GHz,2.3,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,False,1440,900,Intel Core i5 1.8GHz,1.8,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,True,1920,1080,Intel Core i5 7200U 2.5GHz,2.5,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,False,2880,1800,Intel Core i7 2.7GHz,2.7,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 3.1GHz,3.1,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,True,1920,1080,Intel Core i7 6500U 2.5GHz,2.5,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,True,3200,1800,Intel Core i7 6500U 2.5GHz,2.5,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,False,1366,768,Intel Core i7 6500U 2.5GHz,2.5,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

# for save data دا اخر حاجا عملناها

In [30]:
df["Cpu"]

0                       Intel Core i5 2.3GHz
1                       Intel Core i5 1.8GHz
2                 Intel Core i5 7200U 2.5GHz
3                       Intel Core i7 2.7GHz
4                       Intel Core i5 3.1GHz
                        ...
1298              Intel Core i7 6500U 2.5GHz
1299              Intel Core i7 6500U 2.5GHz
1300    Intel Celeron Dual Core N3050 1.6GHz
1301              Intel Core i7 6500U 2.5GHz
1302    Intel Celeron Dual Core N3050 1.6GHz
Name: Cpu, Length: 1303, dtype: object

In [31]:
def get_cpu_core(value: str):
    words = value.split(" ")
    for i, w in enumerate(words):
        if w.lower() == "core":
            return " ".join(words[i:i+2])
    return None

In [32]:
df.insert(
    10,
    "cpu_core",
    df["Cpu"].apply(get_cpu_core)
)

In [33]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,is_HD,width,height,Cpu,cpu_GHz,cpu_core,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 2.3GHz,2.3,Core i5,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,False,1440,900,Intel Core i5 1.8GHz,1.8,Core i5,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,True,1920,1080,Intel Core i5 7200U 2.5GHz,2.5,Core i5,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,False,2880,1800,Intel Core i7 2.7GHz,2.7,Core i7,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 3.1GHz,3.1,Core i5,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,True,1920,1080,Intel Core i7 6500U 2.5GHz,2.5,Core i7,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,True,3200,1800,Intel Core i7 6500U 2.5GHz,2.5,Core i7,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,False,1366,768,Intel Core i7 6500U 2.5GHz,2.5,Core i7,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [34]:
df["Memory"]

0                 128GB SSD
1       128GB Flash Storage
2                 256GB SSD
3                 512GB SSD
4                 256GB SSD
               ...
1298              128GB SSD
1299              512GB SSD
1300     64GB Flash Storage
1301                1TB HDD
1302              500GB HDD
Name: Memory, Length: 1303, dtype: object

In [35]:
def get_cpu_Memory(value: str):

    value = value.split(" ")[0]
    return value
get_cpu_Memory("256GB SSD")

'256GB'

In [36]:
df.insert(
    13,
    "Memory_size",
    df["Memory"].apply(get_cpu_Memory)
)

In [37]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,is_HD,width,height,Cpu,cpu_GHz,cpu_core,Ram,Memory,Memory_size,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 2.3GHz,2.3,Core i5,8GB,128GB SSD,128GB,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,False,1440,900,Intel Core i5 1.8GHz,1.8,Core i5,8GB,128GB Flash Storage,128GB,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,True,1920,1080,Intel Core i5 7200U 2.5GHz,2.5,Core i5,8GB,256GB SSD,256GB,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,False,2880,1800,Intel Core i7 2.7GHz,2.7,Core i7,16GB,512GB SSD,512GB,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 3.1GHz,3.1,Core i5,8GB,256GB SSD,256GB,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,True,1920,1080,Intel Core i7 6500U 2.5GHz,2.5,Core i7,4GB,128GB SSD,128GB,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,True,3200,1800,Intel Core i7 6500U 2.5GHz,2.5,Core i7,16GB,512GB SSD,512GB,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,2GB,64GB Flash Storage,64GB,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,False,1366,768,Intel Core i7 6500U 2.5GHz,2.5,Core i7,6GB,1TB HDD,1TB,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,4GB,500GB HDD,500GB,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [38]:
df["Gpu"]

0       Intel Iris Plus Graphics 640
1             Intel HD Graphics 6000
2              Intel HD Graphics 620
3                 AMD Radeon Pro 455
4       Intel Iris Plus Graphics 650
                    ...
1298           Intel HD Graphics 520
1299           Intel HD Graphics 520
1300               Intel HD Graphics
1301              AMD Radeon R5 M330
1302               Intel HD Graphics
Name: Gpu, Length: 1303, dtype: object

In [39]:
def get_cpu_Gpu(value: str):

    value = value.split(" ")[0] 
    return value
get_cpu_Gpu("Intel HD Graphics 520")

'Intel'

In [40]:
def get_Gpu(value: str):
    keywords = ["Intel", "AMD", "NVIDIA", "HD", "UHD", "Radeon", "GeForce", "Iris"]
    words = value.split(" ")
    result = [w for w in words if w in keywords]
    return " ".join(result)

In [41]:
df.insert(
    15,
    "type_Gpu",
    df["Gpu"].apply(get_Gpu)
)

In [42]:
df

,Company,TypeName,Inches,ScreenResolution,is_touch_screen,is_HD,width,height,Cpu,cpu_GHz,cpu_core,Ram,Memory,Memory_size,Gpu,type_Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 2.3GHz,2.3,Core i5,8GB,128GB SSD,128GB,Intel Iris Plus Graphics 640,Intel Iris,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,False,False,1440,900,Intel Core i5 1.8GHz,1.8,Core i5,8GB,128GB Flash Storage,128GB,Intel HD Graphics 6000,Intel HD,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,False,True,1920,1080,Intel Core i5 7200U 2.5GHz,2.5,Core i5,8GB,256GB SSD,256GB,Intel HD Graphics 620,Intel HD,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,False,False,2880,1800,Intel Core i7 2.7GHz,2.7,Core i7,16GB,512GB SSD,512GB,AMD Radeon Pro 455,AMD Radeon,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,False,False,2560,1600,Intel Core i5 3.1GHz,3.1,Core i5,8GB,256GB SSD,256GB,Intel Iris Plus Graphics 650,Intel Iris,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,True,True,1920,1080,Intel Core i7 6500U 2.5GHz,2.5,Core i7,4GB,128GB SSD,128GB,Intel HD Graphics 520,Intel HD,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,True,True,3200,1800,Intel Core i7 6500U 2.5GHz,2.5,Core i7,16GB,512GB SSD,512GB,Intel HD Graphics 520,Intel HD,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,2GB,64GB Flash Storage,64GB,Intel HD Graphics,Intel HD,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,False,False,1366,768,Intel Core i7 6500U 2.5GHz,2.5,Core i7,6GB,1TB HDD,1TB,AMD Radeon R5 M330,AMD Radeon,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,False,False,1366,768,Intel Celeron Dual Core N3050 1.6GHz,1.6,Core N3050,4GB,500GB HDD,500GB,Intel HD Graphics,Intel HD,Windows 10,2.2kg,19660.3200

In [43]:
df.to_csv("../data/feature_engineered/feature_engineered_data.csv")